export const ADD_ALERT = "ADD_ALERT";
export const ADD_ALERT_SUCCESS = "ADD_ALERT_SUCCESS";
export const UPDATE_ALERT = "UPDATE_ALERT";
export const UPDATE_ALERT_SUCCESS = "UPDATE_ALERT_SUCCESS";
export const DELETE_ALERT = "DELETE_ALERT";
export const DELETE_ALERT_SUCCESS = "DELETE_ALERT_SUCCESS";
